name: Push to GitFlic

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git Remote
        run: |
          git remote set-url origin https://${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/${{ secrets.GITFLIC_ORG }}/autismsmartdetector.git

      - name: Push to GitFlic
        run: |
          git push origin main
